//this file contains all displayed strings
import React from "react";

export const searchMultiselect = 'Search Here...';
export const nonSelectedText = 'Select a value';
export const textButtonShow = 'Show';
export const textNewLayout = 'New Layout';
export const textLayoutSaving = 'Layout Saving';
export const textLabelModal = 'Insert name: ';
export const textButtonSave = 'Save';
export const textButtonClose = 'Close';
export const textLayouts = 'Layouts';
export const textButtonAdd = 'ADD';
export const textButtonReset = 'RESET';
export const textSearch = 'Search...';
export const namePTable = 'NAME';
export const genderPTable = 'GENDER';
export const dateBirthPTable = 'DATE OF BIRTH';
export const bloodPTable = 'BLOOD TYPE';
export const heightTable = 'HEIGHT';
export const visitDateTable = 'VISIT DATE';
export const infoTable = 'INFORMATION';
export const measTable = 'MEASUREMENT';
export const valueTable = 'VALUE';
export const noteTitle = 'NOTE';
export const nullNote = 'NO NOTE';
export const noPatientSel = 'NO PATIENT SELECTED';
export const ageLab = 'AGE';
export const sexLab = 'SEX';
export const bloodLab = 'BLOOD';
export const tablePatientsText = 'PATIENTS';
export const tableVisitText = 'PATIENT VISITS';
export const visitInfoText = 'VISIT INFORMATION';
export const vitalSignsText = 'VITAL SIGNS';
export const graphTitleText = 'VALUES MEASURED';
export const timelineTitleText = 'TIMELINE';